services:
  triton:
    image: nvcr.io/nvidia/tritonserver:24.09-py3
    container_name: triton
    restart: unless-stopped
    runtime: nvidia
    shm_size: "1g"
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      TRITON_MODEL_CONTROL_MODE: "poll"
      NVIDIA_VISIBLE_DEVICES: "all" # 要鎖卡才改成 "0" 或 "0,2"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./models:/models
    command: >
      tritonserver
      --model-repository=/models
      --strict-model-config=false
      --exit-on-error=false
      --allow-http=true
      --allow-grpc=true
      --metrics-port=8002
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/v2/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 12
