services:
  triton:
    image: nvcr.io/nvidia/tritonserver:25.01-py3
    container_name: triton
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: "1g"
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./models:/models
    command: >
      tritonserver
      --model-repository=/models
      --model-control-mode=poll
      --repository-poll-secs=5
      --exit-on-error=false
      --allow-http=true
      --allow-grpc=true
      --metrics-port=8002
